### ISSUE TITLE
"Request is not defined" from node-postgrest backend

### ISSUE THREAD

**Issue by photz** [subzerocloud/showcase#4]
Hi, 
I followed the instructions for the node-postgrest showcase and am getting a 500 from the backend when I try some of the endpoints.

For example:

```
$ curl -i "http://localhost:3000/Products?select=ProductID&limit=3"
HTTP/1.1 500 Internal Server Error
content-type: application/json
Date: Fri, 17 Feb 2023 07:30:49 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

{"message":"Request is not defined","description":null}
```

This seems to be where this message is returned: https://github.com/subzerocloud/showcase/blob/main/node-postgrest/src/server.ts#L289

Environment:
Node v16.11.0
Docker version 20.10.14
Ubuntu 18.04

**Comment by ruslantalpa** [comment]
It seems the Request object is supported from node 18+ (I tested on 19)

See if you can run it with a newer version of node. However, i will look into supporting older versions of node this weekend

Let me know how it went

thanks

**Comment by photz** [comment]
Hi, thanks for the quick response. It works with Node 19. Should've thought of that myself before posting the issue. Sorry!
